# Auto-generated by `npm run sync` — local changes will be overwritten.
# Builds the site on pull requests to verify nothing is broken.
name: CI

on:
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: LFS cache period
        id: lfs-period
        run: echo "period=$(( $(date +%s) / 1209600 ))" >> "$GITHUB_OUTPUT"

      - name: Restore LFS cache
        uses: actions/cache@v5
        with:
          path: .git/lfs
          key: lfs-${{ steps.lfs-period.outputs.period }}
          restore-keys: lfs-

      - name: Pull LFS files
        run: git lfs pull

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - name: Generate map styles
        run: npx tsx node_modules/whereto-bike/scripts/build-map-style.ts

      - name: Restore Astro content cache
        uses: actions/cache@v5
        with:
          path: .astro
          key: astro-${{ hashFiles('blog/**') }}
          restore-keys: astro-

      - name: Build site
        run: npx astro build
        env:
          CONTENT_DIR: .
          CITY: blog
          SITE_URL: https://{{DOMAIN}}
          NODE_OPTIONS: '--max-old-space-size=4096'
