# Auto-generated by `npm run sync` — local changes will be overwritten.
# Builds and deploys the site to Cloudflare Workers on push to main.
name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v6

      - name: LFS cache period
        id: lfs-period
        run: echo "period=$(( $(date +%s) / 1209600 ))" >> "$GITHUB_OUTPUT"

      - name: Restore LFS cache
        uses: actions/cache@v5
        with:
          path: .git/lfs
          key: lfs-${{ steps.lfs-period.outputs.period }}
          restore-keys: lfs-

      - name: Pull LFS files
        run: git lfs pull

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - name: Record build start time
        run: echo "BUILD_START=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$GITHUB_ENV"

      - name: Generate map styles
        run: npx tsx node_modules/whereto-bike/scripts/build-map-style.ts

      - name: Restore map cache
        uses: actions/cache@v5
        with:
          path: public/maps
          key: maps-${{ hashFiles('blog/rides/**/*.gpx', 'package-lock.json') }}
          restore-keys: maps-

      - name: Restore Astro content cache
        uses: actions/cache@v5
        with:
          path: .astro
          key: astro-${{ github.run_id }}
          restore-keys: astro-

      - name: Restore dist cache
        uses: actions/cache@v5
        with:
          path: dist-cache
          key: dist-blog-${{ github.run_id }}
          restore-keys: |
            dist-blog-

      - name: Generate map thumbnails
        run: npx tsx node_modules/whereto-bike/scripts/generate-maps.ts
        env:
          CONTENT_DIR: .
          CITY: blog
          GOOGLE_MAPS_STATIC_API_KEY: ${{ secrets.GOOGLE_MAPS_STATIC_API_KEY }}

      - name: Prepare build plan
        run: npx tsx node_modules/whereto-bike/scripts/prepare-build-plan.ts
        env:
          CONTENT_DIR: .
          CITY: blog

      - name: Resolve VIDEO_PREFIX from wrangler config
        id: video-prefix
        run: |
          PREFIX=$(sed 's|//.*$||' wrangler.jsonc | jq -r '.vars.VIDEO_PREFIX // empty')
          echo "value=${PREFIX}" >> "$GITHUB_OUTPUT"

      - name: Build site
        run: npx astro build
        env:
          CONTENT_DIR: .
          CITY: blog
          SITE_URL: https://{{DOMAIN}}
          VIDEO_PREFIX: ${{ steps.video-prefix.outputs.value }}
          NODE_OPTIONS: '--max-old-space-size=4096'

      - name: Merge incremental build
        run: npx tsx node_modules/whereto-bike/scripts/merge-incremental-build.ts

      - name: Prepare wrangler config
        run: |
          rm -f dist/server/wrangler.json
          node -e "
            const fs = require('fs');
            const raw = fs.readFileSync('wrangler.jsonc', 'utf8');
            const stripped = raw.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
            const c = JSON.parse(stripped);
            c.main = './dist/server/entry.mjs';
            c.assets.directory = './dist/client';
            fs.writeFileSync('wrangler.jsonc', JSON.stringify(c, null, 2));
          "

      - name: Run D1 migrations
        run: npx wrangler d1 migrations apply DB --config wrangler.jsonc --remote
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy to Cloudflare Workers
        run: npx wrangler deploy --config wrangler.jsonc
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Clear stale content edits cache
        run: npx wrangler d1 execute DB --config wrangler.jsonc --remote --command "DELETE FROM content_edits WHERE updated_at < '${{ env.BUILD_START }}'"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-lambda:
    if: vars.VIDEO_PREFIX != '' && vars.SKIP_LAMBDA_DEPLOY != 'true'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - run: npm ci

      - name: Run Lambda tests
        run: node --test node_modules/whereto-bike/aws/video-agent/handler.test.mjs

      - name: Package and deploy Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          cd node_modules/whereto-bike/aws/video-agent
          npm ci --omit=dev
          zip -r function.zip handler.mjs package.json node_modules/
          aws lambda update-function-code \
            --function-name video-agent \
            --zip-file fileb://function.zip \
            --publish
