# Auto-generated by `npm run sync` — local changes will be overwritten.
# Builds and deploys the site to Cloudflare Workers on push to main.
name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v6

      - name: LFS cache period
        id: lfs-period
        run: echo "period=$(( $(date +%s) / 1209600 ))" >> "$GITHUB_OUTPUT"

      - name: Restore LFS cache
        uses: actions/cache@v5
        with:
          path: .git/lfs
          key: lfs-${{ steps.lfs-period.outputs.period }}
          restore-keys: lfs-

      - name: Pull LFS files
        run: git lfs pull

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - name: Record build start time
        run: echo "BUILD_START=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$GITHUB_ENV"

      - name: Generate map styles
        run: npx tsx node_modules/bike-app-astro/scripts/build-map-style.ts

      - name: Map cache period
        id: map-period
        run: echo "period=$(( $(date +%s) / 2592000 ))" >> "$GITHUB_OUTPUT"

      - name: Restore map cache
        uses: actions/cache@v5
        with:
          path: public/maps
          key: maps-${{ steps.map-period.outputs.period }}
          restore-keys: maps-

      - name: Restore Astro content cache
        uses: actions/cache@v5
        with:
          path: .astro
          key: astro-${{ hashFiles('{{USERNAME}}/rides/**/*.gpx') }}
          restore-keys: astro-

      - name: Generate map thumbnails
        run: npx tsx node_modules/bike-app-astro/scripts/generate-maps.ts
        env:
          CONTENT_DIR: .
          CITY: {{USERNAME}}
          GOOGLE_MAPS_STATIC_API_KEY: ${{ secrets.GOOGLE_MAPS_STATIC_API_KEY }}

      - name: Build site
        run: npx astro build
        env:
          CONTENT_DIR: .
          CITY: {{USERNAME}}
          SITE_URL: https://{{DOMAIN}}
          NODE_OPTIONS: '--max-old-space-size=4096'

      - name: Prepare wrangler config
        run: |
          rm -f dist/server/wrangler.json
          node -e "
            const fs = require('fs');
            const raw = fs.readFileSync('wrangler.jsonc', 'utf8');
            const stripped = raw.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
            const c = JSON.parse(stripped);
            c.main = './dist/server/entry.mjs';
            c.assets.directory = './dist/client';
            fs.writeFileSync('wrangler.jsonc', JSON.stringify(c, null, 2));
          "

      - name: Run D1 migrations
        run: npx wrangler d1 migrations apply DB --config wrangler.jsonc --remote
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy to Cloudflare Workers
        run: npx wrangler deploy --config wrangler.jsonc
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Clear stale content edits cache
        run: npx wrangler d1 execute DB --config wrangler.jsonc --remote --command "DELETE FROM content_edits WHERE updated_at < '${{ env.BUILD_START }}'"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
