# Auto-generated by `npm run sync` — local changes will be overwritten.
# Weekly: updates bike-app-astro, syncs templates, commits and pushes if changed.
name: Update

on:
  schedule:
    - cron: '0 9 * * 1' # Every Monday at 9am UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: LFS cache period
        id: lfs-period
        run: echo "period=$(( $(date +%s) / 1209600 ))" >> "$GITHUB_OUTPUT"

      - name: Restore LFS cache
        uses: actions/cache@v5
        with:
          path: .git/lfs
          key: lfs-${{ steps.lfs-period.outputs.period }}
          restore-keys: lfs-

      - name: Pull LFS files
        run: git lfs pull

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - name: Update bike-app-astro
        run: npm update bike-app-astro

      - name: Sync workflow templates
        run: npm run sync

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "updated=false" >> "$GITHUB_OUTPUT"
          else
            echo "updated=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and push
        if: steps.changes.outputs.updated == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package-lock.json .github/workflows/
          git commit -m "chore: update bike-app-astro"
          git push
