import 'dotenv/config';
import { defineConfig } from 'vitest/config';
import { resolve } from 'node:path';
import { existsSync, writeFileSync } from 'node:fs';
import { buildDataPlugin } from './src/build-data-plugin';

// map-style-url.ts is generated by scripts/build-map-style.ts and may not exist in test/CI.
// Write a stub so tests that import it can resolve the module.
const mapStyleUrlPath = resolve(import.meta.dirname, 'src/lib/map-style-url.ts');
if (!existsSync(mapStyleUrlPath)) {
  writeFileSync(mapStyleUrlPath,
    '// Auto-generated stub for tests — real file created by scripts/build-map-style.ts\n' +
    "export const MAP_STYLE_URL = 'https://example.com/style.json';\n" +
    "export const MAP_STYLE_HC_URL = 'https://example.com/style-hc.json';\n",
  );
}

export default defineConfig({
  plugins: [buildDataPlugin()],
  test: {
    exclude: ['e2e/**', 'node_modules/**', 'docs/**'],
  },
});
