// Auto-generated by `npm run sync` — local changes will be overwritten.
// Interactive setup: provisions Cloudflare resources and configures GitHub secrets.
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import readline from 'node:readline';

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((resolve) => rl.question(q, resolve));

function run(cmd, opts = {}) {
  return execSync(cmd, { encoding: 'utf-8', stdio: opts.stdio || 'pipe', ...opts }).trim();
}

function commandExists(cmd) {
  try {
    execSync(`which ${cmd}`, { stdio: 'pipe' });
    return true;
  } catch {
    return false;
  }
}

function readWranglerConfig() {
  const raw = fs.readFileSync('wrangler.jsonc', 'utf-8');
  const stripped = raw.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
  return JSON.parse(stripped);
}

function hasResourceIds() {
  try {
    const config = readWranglerConfig();
    const db = config.d1_databases?.[0];
    return db?.database_id && db.database_id !== 'TODO';
  } catch {
    return false;
  }
}

function hasGitRemote() {
  try {
    run('git remote get-url origin');
    return true;
  } catch {
    return false;
  }
}

// --- Steps ---

async function stepCloudflare(folderName) {
  console.log('\n  Step 1/3: Cloudflare');
  console.log('  ────────────────────');

  if (hasResourceIds()) {
    console.log('  ✓ Resources already provisioned (wrangler.jsonc has IDs)\n');
    return;
  }

  if (!commandExists('wrangler')) {
    console.log('  ✗ wrangler not found\n');
    console.log('  You can install it with: npm i -g wrangler\n');
    console.log('  Or set up Cloudflare manually:');
    console.log(`    1. Create a D1 database named "${folderName}-db"`);
    console.log(`    2. Create an R2 bucket named "${folderName}-media"`);
    console.log(`    3. Create a KV namespace for TILE_CACHE`);
    console.log('    4. Add the resource IDs to wrangler.jsonc\n');

    const answer = await ask('  Continue without wrangler? [Y/n] ');
    if (answer.toLowerCase() === 'n') {
      console.log('\n  Install wrangler and run npm run setup again.\n');
      process.exit(0);
    }
    console.log('  ⚠ Skipping Cloudflare setup — complete it manually before deploying.\n');
    return;
  }

  // Check login
  try {
    const whoami = run('wrangler whoami');
    const accountMatch = whoami.match(/(\S+@\S+)/);
    console.log(`  ✓ wrangler found, logged in as ${accountMatch?.[1] || 'authenticated'}\n`);
  } catch {
    console.log('  ✗ wrangler not logged in\n');
    const answer = await ask('  Run wrangler login? [Y/n] ');
    if (answer.toLowerCase() === 'n') {
      console.log('\n  Log in with: wrangler login\n  Then run npm run setup again.\n');
      process.exit(0);
    }
    execSync('wrangler login', { stdio: 'inherit' });
    console.log();
  }

  console.log('  I\'ll deploy a placeholder worker to create your database,');
  console.log('  storage, and cache:\n');
  console.log('    wrangler deploy --x-provision\n');

  const answer = await ask('  Proceed? [Y/n] ');
  if (answer.toLowerCase() === 'n') {
    console.log('\n  Skipped. Run npm run setup again when ready.\n');
    return;
  }

  // Create stub worker and ensure dist/ exists (wrangler validates assets.directory)
  fs.mkdirSync('.data', { recursive: true });
  const stubPath = '.data/stub-worker.mjs';
  const distCreated = !fs.existsSync('dist');
  if (distCreated) fs.mkdirSync('dist', { recursive: true });
  fs.writeFileSync(stubPath, 'export default { fetch() { return new Response("Setting up — check back soon!"); } };\n');

  try {
    execSync(`wrangler deploy ${stubPath} --x-provision`, { stdio: 'inherit' });
    console.log('\n  ✓ Resources created, IDs written to wrangler.jsonc\n');
  } catch {
    console.error('\n  ✗ Deploy failed. Check the error above and try again.\n');
    process.exit(1);
  } finally {
    fs.rmSync(stubPath, { force: true });
    if (distCreated) fs.rmSync('dist', { recursive: true, force: true });
  }
}

async function stepGitHub(folderName) {
  console.log('\n  Step 2/3: GitHub');
  console.log('  ────────────────');

  if (!commandExists('gh')) {
    console.log('  ✗ gh not found\n');
    console.log('  You can install it from: https://cli.github.com\n');
    console.log('  Or set up GitHub manually:');
    console.log('    1. Create a repo at github.com');
    console.log('    2. git remote add origin <url>');
    console.log('    3. Add repo secrets in Settings → Secrets → Actions:');
    console.log('       - CLOUDFLARE_API_TOKEN: your Cloudflare API token');
    console.log('       - CLOUDFLARE_ACCOUNT_ID: your account ID\n');

    const answer = await ask('  Continue without gh? [Y/n] ');
    if (answer.toLowerCase() === 'n') {
      console.log('\n  Install gh and run npm run setup again.\n');
      process.exit(0);
    }
    console.log('  ⚠ Skipping GitHub setup — complete it manually.\n');
    return;
  }

  // Check login
  let ghUser;
  try {
    ghUser = run('gh auth status 2>&1').match(/Logged in to .* account (\S+)/)?.[1]
      || run('gh api user -q .login');
  } catch {
    console.log('  ✗ gh not logged in\n');
    const answer = await ask('  Run gh auth login? [Y/n] ');
    if (answer.toLowerCase() === 'n') {
      console.log('\n  Log in with: gh auth login\n  Then run npm run setup again.\n');
      process.exit(0);
    }
    execSync('gh auth login', { stdio: 'inherit' });
    ghUser = run('gh api user -q .login');
  }
  console.log(`  ✓ gh found, logged in as ${ghUser}\n`);

  // Collect what we need to do
  const needsRepo = !hasGitRemote();
  const repoName = `${ghUser}/${folderName}`;

  // Token
  console.log('  GitHub Actions needs a Cloudflare API token to deploy.\n');
  console.log('  Create one at:');
  console.log('    https://dash.cloudflare.com/profile/api-tokens\n');
  console.log('  Click "Create Token", then "Edit Cloudflare Workers" → "Use template".');
  console.log('  On the next screen:');
  console.log('    - Add permission: Account → D1 → Edit');
  console.log('    - Add permission: Account → Workers R2 Storage → Edit');
  console.log('    - Account Resources: pick your account');
  console.log('    - Zone Resources: "All zones" (or pick your domain)');
  console.log('  Click "Continue to summary" → "Create Token" → copy it.\n');

  const token = await ask('  Paste your token: ');
  if (!token.trim()) {
    console.log('\n  No token provided. Run npm run setup again when ready.\n');
    return;
  }

  // Get account ID
  let accountId;
  try {
    const whoami = run('wrangler whoami 2>/dev/null');
    accountId = whoami.match(/([a-f0-9]{32})/)?.[1];
  } catch { /* ignore */ }

  if (!accountId) {
    accountId = await ask('  Paste your Cloudflare Account ID: ');
  }

  // Show what we'll do
  console.log('\n  I\'ll run:\n');
  if (needsRepo) {
    console.log(`    gh repo create ${repoName} --private --source .`);
  }
  console.log('    gh secret set CLOUDFLARE_API_TOKEN');
  console.log(`    gh secret set CLOUDFLARE_ACCOUNT_ID (${accountId?.slice(0, 8)}...)`);
  console.log();

  const answer = await ask('  Proceed? [Y/n] ');
  if (answer.toLowerCase() === 'n') {
    console.log('\n  Skipped. Run npm run setup again when ready.\n');
    return;
  }

  if (needsRepo) {
    try {
      execSync(`gh repo create ${repoName} --private --source .`, { stdio: 'inherit' });
      console.log(`\n  ✓ Repo created: github.com/${repoName}`);
    } catch {
      console.error('\n  ✗ Repo creation failed. Create it manually and run setup again.\n');
      return;
    }
  }

  // Set secrets
  try {
    const secretInput = (name, value) => {
      execSync(`gh secret set ${name}`, {
        input: value,
        stdio: ['pipe', 'pipe', 'pipe'],
      });
    };
    secretInput('CLOUDFLARE_API_TOKEN', token.trim());
    secretInput('CLOUDFLARE_ACCOUNT_ID', accountId.trim());
    console.log('  ✓ Secrets configured\n');
  } catch {
    console.error('\n  ✗ Failed to set secrets. Set them manually in repo Settings → Secrets.\n');
  }
}

async function stepApiKeys() {
  console.log('\n  Step 3/3: API Keys');
  console.log('  ──────────────────');

  if (!commandExists('wrangler')) {
    console.log('  ⚠ wrangler not found — skipping. Set these secrets manually before deploying.\n');
    return;
  }

  // --- Auto-detect what we can ---
  const autoSecrets = [];
  const autoVars = [];

  // R2_BUCKET_NAME from wrangler.jsonc (created in Step 1)
  try {
    const config = readWranglerConfig();
    const bucketName = config.r2_buckets?.[0]?.bucket_name;
    if (bucketName) autoSecrets.push({ name: 'R2_BUCKET_NAME', value: bucketName });
  } catch { /* ignore */ }

  // R2_ACCOUNT_ID from wrangler whoami (already logged in from Step 1)
  try {
    const whoami = run('wrangler whoami 2>/dev/null');
    const id = whoami.match(/([a-f0-9]{32})/)?.[1];
    if (id) autoSecrets.push({ name: 'R2_ACCOUNT_ID', value: id });
  } catch { /* ignore */ }

  // GIT_OWNER and GIT_DATA_REPO from git remote (blog content lives in same repo)
  try {
    const remoteUrl = run('git remote get-url origin');
    const match = remoteUrl.match(/github\.com[:/]([^/]+)\/([^/.]+)/);
    if (match) {
      autoVars.push({ name: 'GIT_OWNER', value: match[1] });
      autoVars.push({ name: 'GIT_DATA_REPO', value: match[2] });
    }
  } catch { /* ignore */ }

  if (autoSecrets.length > 0 || autoVars.length > 0) {
    console.log('  Auto-detected from your setup:\n');
    for (const { name, value } of [...autoVars, ...autoSecrets]) {
      console.log(`    ${name} = ${value}`);
    }
    console.log();
  }

  // --- Prompt only for secrets that need manual input ---
  console.log('  A few API keys are needed for full functionality. Press Enter to skip any.\n');

  const secrets = [
    {
      name: 'GITHUB_TOKEN',
      description: 'Personal access token for saving content edits',
      howTo: 'GitHub → Settings → Developer settings → Personal access tokens\n    → Fine-grained → Create: repo contents read/write on this repo',
    },
    {
      name: 'R2_ACCESS_KEY_ID',
      description: 'R2 API key ID for photo upload (presigned URLs)',
      howTo: 'Cloudflare Dashboard → R2 → Manage R2 API Tokens\n    → Create API token → read/write on your bucket → copy Access Key ID',
    },
    {
      name: 'R2_SECRET_ACCESS_KEY',
      description: 'R2 API secret for photo upload (presigned URLs)',
      howTo: 'Same token as R2_ACCESS_KEY_ID — copy the Secret Access Key',
    },
    {
      name: 'R2_PUBLIC_URL',
      description: 'Public URL for your media/images CDN bucket',
      howTo: 'Your R2 bucket\'s public URL (custom domain or r2.dev URL)',
    },
    {
      name: 'THUNDERFOREST_API_KEY',
      description: 'Map tiles (cycle, outdoors, transport layers)',
      howTo: 'https://www.thunderforest.com → sign up → Dashboard → API key',
    },
    {
      name: 'GOOGLE_PLACES_API_KEY',
      description: 'Auto-populating place details when adding places',
      howTo: 'Google Cloud Console → APIs & Services → Credentials\n    → Create API Key → Enable Places API',
    },
    {
      name: 'RWGPS_API_KEY',
      description: 'Import routes from RideWithGPS',
      howTo: 'https://ridewithgps.com/api → request API access',
    },
    {
      name: 'RWGPS_AUTH_TOKEN',
      description: 'Auth token for RideWithGPS API (paired with API key)',
      howTo: 'Same as RWGPS_API_KEY — provided alongside it',
    },
  ];

  const vars = [
    {
      name: 'WEBAUTHN_RP_ID',
      description: 'WebAuthn relying party domain (for passkey login)',
      howTo: 'Your domain without protocol (e.g. "eljojo.bike")',
    },
    {
      name: 'WEBAUTHN_RP_NAME',
      description: 'Display name shown in passkey prompts',
      howTo: 'Your blog name (e.g. "El Jojo Bike")',
    },
    {
      name: 'WEBAUTHN_ORIGIN',
      description: 'Full origin URL for WebAuthn',
      howTo: 'Your full URL with protocol (e.g. "https://eljojo.bike")',
    },
  ];

  const collectedSecrets = [...autoSecrets];
  const collectedVars = [...autoVars];

  for (const s of secrets) {
    console.log(`  ${s.name}`);
    console.log(`    ${s.description}`);
    console.log(`    ${s.howTo}\n`);
    const value = await ask('    Value: ');
    if (value.trim()) {
      collectedSecrets.push({ name: s.name, value: value.trim() });
    } else {
      console.log('    → skipped\n');
    }
  }

  for (const v of vars) {
    console.log(`  ${v.name}`);
    console.log(`    ${v.description}`);
    console.log(`    ${v.howTo}\n`);
    const value = await ask('    Value: ');
    if (value.trim()) {
      collectedVars.push({ name: v.name, value: value.trim() });
    } else {
      console.log('    → skipped\n');
    }
  }

  // Set secrets via wrangler
  for (const { name, value } of collectedSecrets) {
    try {
      execSync(`wrangler secret put ${name}`, {
        input: value,
        stdio: ['pipe', 'pipe', 'pipe'],
      });
      console.log(`  ✓ ${name} set`);
    } catch {
      console.error(`  ✗ Failed to set ${name} — set it manually with: wrangler secret put ${name}`);
    }
  }

  // Set vars in wrangler.jsonc
  if (collectedVars.length > 0) {
    try {
      const raw = fs.readFileSync('wrangler.jsonc', 'utf-8');
      let updated = raw;

      if (/"vars"\s*:/.test(updated)) {
        for (const { name, value } of collectedVars) {
          const varsMatch = updated.match(/"vars"\s*:\s*\{/);
          if (varsMatch) {
            const insertPos = varsMatch.index + varsMatch[0].length;
            updated = updated.slice(0, insertPos) + `\n    "${name}": "${value}",` + updated.slice(insertPos);
          }
        }
      } else {
        const lastBrace = updated.lastIndexOf('}');
        const varsObj = collectedVars.map(({ name, value }) => `    "${name}": "${value}"`).join(',\n');
        updated = updated.slice(0, lastBrace) + `  "vars": {\n${varsObj}\n  },\n` + updated.slice(lastBrace);
      }

      fs.writeFileSync('wrangler.jsonc', updated);
      console.log(`  ✓ ${collectedVars.map(v => v.name).join(', ')} added to wrangler.jsonc`);
    } catch {
      console.error('  ⚠ Could not update wrangler.jsonc — add these vars manually:');
      for (const { name, value } of collectedVars) {
        console.error(`    "${name}": "${value}"`);
      }
    }
  }

  const prompted = collectedSecrets.length - autoSecrets.length + collectedVars.length - autoVars.length;
  if (prompted === 0) {
    console.log('  No additional keys set. You can add them later with: wrangler secret put <NAME>\n');
  } else {
    console.log();
  }
}

// --- Main ---

async function main() {
  const pkg = JSON.parse(fs.readFileSync('package.json', 'utf-8'));
  const folderName = pkg.name;

  console.log(`\n  Setting up ${folderName} for deployment.`);

  await stepCloudflare(folderName);
  await stepGitHub(folderName);
  await stepApiKeys();

  // Offer to commit and push
  let remoteUrl;
  try {
    remoteUrl = run('git remote get-url origin');
  } catch { /* no remote */ }

  if (remoteUrl) {
    console.log('  ──────────────────────');
    const deploy = await ask('  Commit and push to trigger first deploy? [Y/n] ');
    if (deploy.toLowerCase() !== 'n') {
      execSync('git add wrangler.jsonc', { stdio: 'pipe' });
      try {
        execSync('git commit -m "setup complete"', { stdio: 'pipe' });
      } catch {
        // nothing to commit — that's fine
      }
      execSync('git push -u origin main', { stdio: 'inherit' });

      const actionsUrl = remoteUrl
        .replace(/\.git$/, '')
        .replace('git@github.com:', 'https://github.com/')
        + '/actions';
      console.log(`\n  ✓ Pushed! Watch your first deploy at:\n\n    ${actionsUrl}\n`);
    } else {
      console.log('\n  When you\'re ready:\n');
      console.log('    git add wrangler.jsonc && git commit -m "setup complete" && git push -u origin main\n');
    }
  } else {
    console.log('  ──────────────────────');
    console.log('  All done! Commit and push to deploy:\n');
    console.log('    git add wrangler.jsonc && git commit -m "setup complete" && git push -u origin main\n');
  }

  // TODO: offer to configure custom domain on Cloudflare

  rl.close();
}

main().catch((err) => {
  console.error('  Error:', err.message);
  process.exit(1);
});
