// Auto-generated by `npm run sync` — local changes will be overwritten.
// Interactive setup: provisions Cloudflare resources and configures GitHub secrets.
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import readline from 'node:readline';

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((resolve) => rl.question(q, resolve));

function run(cmd, opts = {}) {
  return execSync(cmd, { encoding: 'utf-8', stdio: opts.stdio || 'pipe', ...opts }).trim();
}

function commandExists(cmd) {
  try {
    execSync(`which ${cmd}`, { stdio: 'pipe' });
    return true;
  } catch {
    return false;
  }
}

function readWranglerConfig() {
  const raw = fs.readFileSync('wrangler.jsonc', 'utf-8');
  const stripped = raw.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
  return JSON.parse(stripped);
}

function hasResourceIds() {
  try {
    const config = readWranglerConfig();
    const db = config.d1_databases?.[0];
    return db?.database_id && db.database_id !== 'TODO';
  } catch {
    return false;
  }
}

function wranglerCmd() {
  return commandExists('wrangler') ? 'wrangler' : 'npx wrangler';
}

function hasWrangler() {
  return commandExists('wrangler') || commandExists('npx');
}

function readDomain() {
  try {
    const content = fs.readFileSync('blog/config.yml', 'utf-8');
    const match = content.match(/^domain:\s*(.+)$/m);
    if (match) return match[1].trim();
  } catch { /* ignore */ }
  return null;
}

function hasGitRemote() {
  try {
    run('git remote get-url origin');
    return true;
  } catch {
    return false;
  }
}

// --- Steps ---

async function stepCloudflare(folderName) {
  console.log('\n  Step 1/3: Cloudflare');
  console.log('  ────────────────────');

  if (hasResourceIds()) {
    console.log('  ✓ Resources already provisioned (wrangler.jsonc has IDs)\n');
    return;
  }

  if (!hasWrangler()) {
    console.log('  ✗ wrangler not found\n');
    console.log('  You can install it with: npm i -g wrangler\n');
    console.log('  Or set up Cloudflare manually:');
    console.log(`    1. Create a D1 database named "${folderName}-db"`);
    console.log(`    2. Create an R2 bucket named "${folderName}-media"`);
    console.log(`    3. Create a KV namespace for TILE_CACHE`);
    console.log('    4. Add the resource IDs to wrangler.jsonc\n');

    const answer = await ask('  Continue without wrangler? [Y/n] ');
    if (answer.toLowerCase() === 'n') {
      console.log('\n  Install wrangler and run npm run setup again.\n');
      process.exit(0);
    }
    console.log('  ⚠ Skipping Cloudflare setup — complete it manually before deploying.\n');
    return;
  }

  // Check login
  try {
    const whoami = run(`${wranglerCmd()} whoami`);
    const accountMatch = whoami.match(/(\S+@\S+)/);
    console.log(`  ✓ wrangler found, logged in as ${accountMatch?.[1] || 'authenticated'}\n`);
  } catch {
    console.log('  ✗ wrangler not logged in\n');
    const answer = await ask('  Run wrangler login? [Y/n] ');
    if (answer.toLowerCase() === 'n') {
      console.log('\n  Log in with: wrangler login\n  Then run npm run setup again.\n');
      process.exit(0);
    }
    execSync(`${wranglerCmd()} login`, { stdio: 'inherit' });
    console.log();
  }

  console.log('  I\'ll deploy a placeholder worker to create your database,');
  console.log('  storage, and cache:\n');
  console.log('    wrangler deploy --x-provision\n');

  const answer = await ask('  Proceed? [Y/n] ');
  if (answer.toLowerCase() === 'n') {
    console.log('\n  Skipped. Run npm run setup again when ready.\n');
    return;
  }

  // Create stub worker and ensure dist/ exists (wrangler validates assets.directory)
  fs.mkdirSync('.data', { recursive: true });
  const stubPath = '.data/stub-worker.mjs';
  const distCreated = !fs.existsSync('dist');
  if (distCreated) fs.mkdirSync('dist', { recursive: true });
  fs.writeFileSync(stubPath, 'export default { fetch() { return new Response("Setting up — check back soon!"); } };\n');

  try {
    execSync(`${wranglerCmd()} deploy ${stubPath} --x-provision`, { stdio: 'inherit' });
    console.log('\n  ✓ Resources created, IDs written to wrangler.jsonc\n');
  } catch {
    console.error('\n  ✗ Deploy failed. Check the error above and try again.\n');
    process.exit(1);
  } finally {
    fs.rmSync(stubPath, { force: true });
    if (distCreated) fs.rmSync('dist', { recursive: true, force: true });
  }
}

async function stepGitHub(folderName) {
  console.log('\n  Step 2/3: GitHub');
  console.log('  ────────────────');

  if (!commandExists('gh')) {
    console.log('  ✗ gh not found\n');
    console.log('  You can install it from: https://cli.github.com\n');
    console.log('  Or set up GitHub manually:');
    console.log('    1. Create a repo at github.com');
    console.log('    2. git remote add origin <url>');
    console.log('    3. Add repo secrets in Settings → Secrets → Actions:');
    console.log('       - CLOUDFLARE_API_TOKEN: your Cloudflare API token');
    console.log('       - CLOUDFLARE_ACCOUNT_ID: your account ID\n');

    const answer = await ask('  Continue without gh? [Y/n] ');
    if (answer.toLowerCase() === 'n') {
      console.log('\n  Install gh and run npm run setup again.\n');
      process.exit(0);
    }
    console.log('  ⚠ Skipping GitHub setup — complete it manually.\n');
    return;
  }

  // Check login
  let ghUser;
  try {
    ghUser = run('gh auth status 2>&1').match(/Logged in to .* account (\S+)/)?.[1]
      || run('gh api user -q .login');
  } catch {
    console.log('  ✗ gh not logged in\n');
    const answer = await ask('  Run gh auth login? [Y/n] ');
    if (answer.toLowerCase() === 'n') {
      console.log('\n  Log in with: gh auth login\n  Then run npm run setup again.\n');
      process.exit(0);
    }
    execSync('gh auth login', { stdio: 'inherit' });
    ghUser = run('gh api user -q .login');
  }
  console.log(`  ✓ gh found, logged in as ${ghUser}\n`);

  // Create repo if needed
  const needsRepo = !hasGitRemote();
  const repoName = `${ghUser}/${folderName}`;

  if (needsRepo) {
    console.log(`  I'll create a private repo:\n`);
    console.log(`    gh repo create ${repoName} --private --source .\n`);
    const createAnswer = await ask('  Proceed? [Y/n] ');
    if (createAnswer.toLowerCase() !== 'n') {
      try {
        execSync(`gh repo create ${repoName} --private --source .`, { stdio: 'inherit' });
        console.log(`\n  ✓ Repo created: github.com/${repoName}\n`);
      } catch {
        console.error('\n  ✗ Repo creation failed. Create it manually and run setup again.\n');
      }
    }
  } else {
    console.log('  ✓ Repo already configured\n');
  }

  // Check if deploy secrets are already set
  let secretList = '';
  try {
    secretList = run('gh secret list 2>/dev/null');
  } catch { /* ignore — repo may not exist yet */ }

  const hasCfToken = secretList.includes('CLOUDFLARE_API_TOKEN');
  const hasMapsKey = secretList.includes('GOOGLE_MAPS_STATIC_API_KEY');

  if (hasCfToken && hasMapsKey) {
    console.log('  ✓ Deploy secrets already configured\n');
    return;
  }

  const secretInput = (name, value) => {
    execSync(`gh secret set ${name}`, {
      input: value,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
  };

  // Cloudflare deploy token
  if (!hasCfToken) {
    console.log('  GitHub Actions needs a Cloudflare API token to deploy.\n');
    console.log('  Create one at:');
    console.log('    https://dash.cloudflare.com/profile/api-tokens\n');
    console.log('  Click "Create Token", then "Edit Cloudflare Workers" → "Use template".');
    console.log('  On the next screen:');
    console.log('    - Add permission: Account → D1 → Edit');
    console.log('    - Add permission: Account → Workers R2 Storage → Edit');
    console.log('    - Account Resources: pick your account');
    console.log('    - Zone Resources: "All zones" (or pick your domain)');
    console.log('  Click "Continue to summary" → "Create Token" → copy it.\n');

    const token = await ask('  Paste your token (Enter to skip): ');
    if (token.trim()) {
      let accountId;
      try {
        const whoami = run(`${wranglerCmd()} whoami 2>/dev/null`);
        accountId = whoami.match(/([a-f0-9]{32})/)?.[1];
      } catch { /* ignore */ }
      if (!accountId) {
        accountId = await ask('  Paste your Cloudflare Account ID: ');
      }

      try {
        secretInput('CLOUDFLARE_API_TOKEN', token.trim());
        secretInput('CLOUDFLARE_ACCOUNT_ID', accountId.trim());
        console.log('  ✓ Cloudflare deploy secrets configured\n');
      } catch {
        console.error('  ✗ Failed to set Cloudflare secrets. Set them manually in repo Settings → Secrets.\n');
      }
    } else {
      console.log('    → skipped. Set later: gh secret set CLOUDFLARE_API_TOKEN\n');
    }
  } else {
    console.log('  ✓ Cloudflare deploy secrets already configured\n');
  }

  // Google Maps Static API key (for map thumbnail generation during build)
  if (!hasMapsKey) {
    console.log('  Route pages show a static map thumbnail, generated at build time');
    console.log('  using the Google Maps Static API.\n');
    console.log('  Create one at:');
    console.log('    https://console.cloud.google.com/apis/credentials');
    console.log('    → Create API Key → restrict to: Maps Static API\n');
    const mapsKey = await ask('  Google Maps Static API key (Enter to skip): ');
    if (mapsKey.trim()) {
      try {
        secretInput('GOOGLE_MAPS_STATIC_API_KEY', mapsKey.trim());
        console.log('  ✓ GOOGLE_MAPS_STATIC_API_KEY configured\n');
      } catch {
        console.error('  ✗ Failed to set key. Set it manually: gh secret set GOOGLE_MAPS_STATIC_API_KEY\n');
      }
    } else {
      console.log('    → skipped. Routes will build without map thumbnails.');
      console.log('      Set it later: gh secret set GOOGLE_MAPS_STATIC_API_KEY\n');
    }
  }
}

async function stepApiKeys() {
  console.log('\n  Step 3/3: API Keys');
  console.log('  ──────────────────');

  if (!hasWrangler()) {
    console.log('  ⚠ wrangler not found — skipping. Set these secrets manually before deploying.\n');
    return;
  }

  // --- Detect what's already set ---
  let existingSecrets = new Set();
  try {
    const secretList = run(`${wranglerCmd()} secret list 2>/dev/null`);
    const parsed = JSON.parse(secretList);
    existingSecrets = new Set(parsed.map(s => s.name));
  } catch { /* ignore — may not be deployed yet */ }

  let existingVars = new Set();
  try {
    const config = readWranglerConfig();
    if (config.vars) existingVars = new Set(Object.keys(config.vars));
  } catch { /* ignore */ }

  const autoSecrets = [];
  const autoVars = [];

  // R2_BUCKET_NAME from wrangler.jsonc (created in Step 1)
  let bucketName;
  try {
    const config = readWranglerConfig();
    bucketName = config.r2_buckets?.[0]?.bucket_name;
    if (bucketName) autoSecrets.push({ name: 'R2_BUCKET_NAME', value: bucketName });
  } catch { /* ignore */ }

  // R2_ACCOUNT_ID from wrangler whoami (already logged in from Step 1)
  let accountId;
  try {
    const whoami = run(`${wranglerCmd()} whoami 2>/dev/null`);
    accountId = whoami.match(/([a-f0-9]{32})/)?.[1];
    if (accountId) autoSecrets.push({ name: 'R2_ACCOUNT_ID', value: accountId });
  } catch { /* ignore */ }

  // GIT_OWNER and GIT_DATA_REPO from git remote (blog content lives in same repo)
  try {
    const remoteUrl = run('git remote get-url origin');
    const match = remoteUrl.match(/github\.com[:/]([^/]+)\/([^/.]+)/);
    if (match) {
      autoVars.push({ name: 'GIT_OWNER', value: match[1] });
      autoVars.push({ name: 'GIT_DATA_REPO', value: match[2] });
    }
  } catch { /* ignore */ }


  // --- Classify all items ---
  const secrets = [
    {
      name: 'GITHUB_TOKEN', kind: 'secret',
      description: 'Personal access token for saving content edits',
      howTo: 'https://github.com/settings/personal-access-tokens\n    → Fine-grained → select this repo → Permissions:\n      Contents: Read and write',
    },
    {
      name: 'R2_ACCESS_KEY_ID', kind: 'secret',
      description: 'R2 API key ID for photo upload (presigned URLs)',
      howTo: `Cloudflare Dashboard → R2 → Manage R2 API Tokens → Create API token
      Permissions: Object Read & Write
      Specify bucket: ${bucketName || '<your-bucket>'}
    → copy "Access Key ID"`,
    },
    {
      name: 'R2_SECRET_ACCESS_KEY', kind: 'secret',
      description: 'R2 API secret for photo upload (presigned URLs)',
      howTo: 'Same token as above — copy "Secret Access Key"',
    },
    // R2_PUBLIC_URL is handled separately via auto-setup below
    {
      name: 'THUNDERFOREST_API_KEY', kind: 'secret',
      description: 'Map tiles (cycle, outdoors, transport layers)',
      howTo: 'https://www.thunderforest.com → sign up → Dashboard → API key',
    },
    {
      name: 'GOOGLE_PLACES_API_KEY', kind: 'secret',
      description: 'Auto-populating place details when adding places',
      howTo: 'https://console.cloud.google.com/apis/credentials\n    → Create API Key → restrict to: Places API (New)',
    },
    {
      name: 'RWGPS_API_KEY', kind: 'secret',
      description: 'Import routes from RideWithGPS',
      howTo: 'https://ridewithgps.com/api → request API access',
    },
    {
      name: 'RWGPS_AUTH_TOKEN', kind: 'secret',
      description: 'Auth token for RideWithGPS API (paired with API key)',
      howTo: 'Same as RWGPS_API_KEY — provided alongside it',
    },
    {
      name: 'STRAVA_CLIENT_ID', kind: 'secret',
      description: 'Import rides from Strava (optional)',
      howTo: 'https://www.strava.com/settings/api → Create an app → Client ID',
    },
    {
      name: 'STRAVA_CLIENT_SECRET', kind: 'secret',
      description: 'Strava app secret (paired with Client ID)',
      howTo: 'Same app page → Client Secret',
    },
    {
      name: 'SES_ACCESS_KEY_ID', kind: 'secret',
      description: 'AWS IAM access key for sending login emails via Amazon SES',
      howTo: `https://console.aws.amazon.com/iam/home#/users
    1. Create a new IAM user (e.g., "blog-ses-sender")
    2. Attach the "AmazonSESFullAccess" managed policy
    3. Go to Security credentials → Create access key → choose "Application running outside AWS"
    4. Copy the "Access key ID"`,
    },
    {
      name: 'SES_SECRET_ACCESS_KEY', kind: 'secret',
      description: 'AWS IAM secret key (paired with access key above)',
      howTo: 'Same screen as above → copy "Secret access key" (shown only once)',
    },
    {
      name: 'SES_REGION', kind: 'secret',
      description: 'AWS region where your SES identity is verified (e.g., us-east-1)',
      howTo: `https://console.aws.amazon.com/ses/home
    Check the region in the top-right corner of the SES console.
    Common regions: us-east-1, eu-west-1, ap-southeast-2`,
    },
    {
      name: 'SES_FROM', kind: 'secret',
      description: 'From address for login emails (must be verified in SES)',
      howTo: `https://console.aws.amazon.com/ses/home#/verified-identities
    Verify either a domain or a specific email address.
    For a new AWS account in sandbox mode, you must also verify recipient addresses.
    To send to anyone, request production access in the SES console.
    Example: noreply@yourdomain.com`,
    },
    // --- Video Transcoding (optional — needed for video uploads) ---
    {
      name: 'MEDIACONVERT_ACCESS_KEY_ID', kind: 'secret',
      description: 'AWS IAM access key for video transcoding (S3 upload + MediaConvert)',
      howTo: `Video transcoding uses AWS MediaConvert to convert uploaded videos
    into AV1 + H.264 formats with poster frame extraction.

    You need these AWS resources (one-time setup):

    1. Two S3 buckets (one for originals, one for transcoded output):
       https://s3.console.aws.amazon.com/s3/buckets
       → Create bucket (e.g., "myblog-video-originals")
       → Create another (e.g., "myblog-video-outputs")
       No public access needed — the app uses presigned URLs.
       Region: pick one close to you (e.g., us-east-1).
       Both buckets must be in the same region.

    2. An IAM role for MediaConvert:
       https://console.aws.amazon.com/iam/home#/roles
       → Create role → Trusted entity: AWS service → MediaConvert
       → Attach policy: AmazonS3FullAccess (or scope to your two buckets)
       → Name it (e.g., "MediaConvertRole")
       → Copy the Role ARN — you'll need it for MEDIACONVERT_ROLE

    3. An IAM user for the app:
       https://console.aws.amazon.com/iam/home#/users
       → Create user (e.g., "myblog-video")
       → Attach these policies:
         • AmazonS3FullAccess (or scoped to your two buckets)
         • AWSElementalMediaConvertFullAccess
       → Security credentials → Create access key
         → Choose "Application running outside AWS"
       → Copy Access Key ID (paste it here) and Secret Access Key (next prompt)

       If you already have keys from a Rails app using the same AWS resources,
       you can reuse those — the same IAM user works for both.

    4. MediaConvert queue:
       https://console.aws.amazon.com/mediaconvert
       → The "Default" queue is created automatically
       → Queues → Default → copy the ARN (for MEDIACONVERT_QUEUE)

       The API endpoint is auto-discovered at runtime — no need to configure it.`,
    },
    {
      name: 'MEDIACONVERT_SECRET_ACCESS_KEY', kind: 'secret',
      description: 'AWS IAM secret key (paired with access key above)',
      howTo: 'Same IAM user as above — copy "Secret access key" (shown only once when creating the key)',
    },
    {
      name: 'S3_ORIGINALS_BUCKET', kind: 'secret',
      description: 'S3 bucket name for raw video uploads',
      howTo: `The bucket name you created in step 1 for originals (e.g., "myblog-video-originals").
    Just the name, not the full ARN or URL.`,
    },
    {
      name: 'S3_OUTPUTS_BUCKET', kind: 'secret',
      description: 'S3 bucket name for transcoded video output',
      howTo: `The bucket name you created in step 1 for outputs (e.g., "myblog-video-outputs").
    Can be the same bucket as originals if you prefer — transcoded files go into subfolders.`,
    },
    {
      name: 'MEDIACONVERT_QUEUE', kind: 'secret',
      description: 'ARN of the MediaConvert queue',
      howTo: `https://console.aws.amazon.com/mediaconvert → Queues → Default → copy the ARN.
    Looks like: arn:aws:mediaconvert:us-east-1:123456789:queues/Default`,
    },
    {
      name: 'MEDIACONVERT_ROLE', kind: 'secret',
      description: 'IAM role ARN that MediaConvert assumes to read/write S3',
      howTo: `The role you created in step 2 above.
    https://console.aws.amazon.com/iam/home#/roles → find your role → copy the ARN.
    Looks like: arn:aws:iam::123456789:role/MediaConvertRole`,
    },
    {
      name: 'MEDIACONVERT_REGION', kind: 'var',
      description: 'AWS region for your S3 buckets and MediaConvert (e.g., us-east-1)',
      howTo: `The AWS region where you created your S3 buckets and MediaConvert resources.
    All resources must be in the same region. Common choices: us-east-1, eu-west-1, ap-southeast-2`,
    },
  ];

  // Build auto-detected map (name → {name, value, kind}) for items that aren't already set
  const autoDetected = new Map();
  for (const s of autoSecrets) {
    if (!existingSecrets.has(s.name)) autoDetected.set(s.name, { ...s, kind: 'secret' });
  }
  for (const v of autoVars) {
    if (!existingVars.has(v.name)) autoDetected.set(v.name, { ...v, kind: 'var' });
  }

  // Partition into: already set, auto-detected (will set), needs input
  const alreadySet = [];
  const needsInput = [];
  for (const item of secrets) {
    const isSet = item.kind === 'secret'
      ? existingSecrets.has(item.name)
      : existingVars.has(item.name);
    if (isSet) {
      alreadySet.push(item);
    } else if (!autoDetected.has(item.name)) {
      needsInput.push(item);
    }
    // auto-detected items handled separately
  }

  if (alreadySet.length > 0) {
    console.log('  Already configured:');
    for (const item of alreadySet) {
      console.log(`    ✓ ${item.name}`);
    }
    console.log();
  }

  if (autoDetected.size > 0) {
    console.log('  Auto-detected from your setup:');
    for (const [name, { value }] of autoDetected) {
      console.log(`    ${name} = ${value}`);
    }
    console.log();
  }

  // Collect values to write (start with auto-detected, user input appended below)
  const collectedSecrets = [...autoDetected.values()].filter(s => s.kind === 'secret');
  const collectedVars = [...autoDetected.values()].filter(s => s.kind === 'var');

  if (needsInput.length === 0) {
    if (autoDetected.size === 0) {
      console.log('  All keys are set! Nothing to do.\n');
    }
  } else {
    console.log('  A few API keys are needed for full functionality. Press Enter to skip any.\n');

    let skipRemaining = false;
    for (let i = 0; i < needsInput.length; i++) {
      if (skipRemaining) break;
      const item = needsInput[i];

      console.log(`  ${item.name}`);
      console.log(`    ${item.description}`);
      console.log(`    ${item.howTo}\n`);
      const value = await ask('    Value (Enter to skip): ');
      if (value.trim()) {
        if (item.kind === 'secret') {
          collectedSecrets.push({ name: item.name, value: value.trim() });
        } else {
          collectedVars.push({ name: item.name, value: value.trim() });
        }
      } else {
        console.log('    → skipped');
        if (i < needsInput.length - 1) {
          const skipAll = await ask('    Skip remaining keys too? [Y/n] ');
          if (skipAll.toLowerCase() !== 'n') {
            skipRemaining = true;
          }
        }
        console.log();
      }
    }
  }

  // Set secrets via wrangler
  for (const { name, value } of collectedSecrets) {
    try {
      execSync(`${wranglerCmd()} secret put ${name}`, {
        input: value,
        stdio: ['pipe', 'pipe', 'pipe'],
      });
      console.log(`  ✓ ${name} set`);
    } catch {
      console.error(`  ✗ Failed to set ${name} — set it manually with: wrangler secret put ${name}`);
    }
  }

  // Set vars in wrangler.jsonc
  if (collectedVars.length > 0) {
    try {
      const raw = fs.readFileSync('wrangler.jsonc', 'utf-8');
      let updated = raw;

      if (/"vars"\s*:/.test(updated)) {
        for (const { name, value } of collectedVars) {
          const varsMatch = updated.match(/"vars"\s*:\s*\{/);
          if (varsMatch) {
            const insertPos = varsMatch.index + varsMatch[0].length;
            updated = updated.slice(0, insertPos) + `\n    "${name}": "${value}",` + updated.slice(insertPos);
          }
        }
      } else {
        const lastBrace = updated.lastIndexOf('}');
        const varsObj = collectedVars.map(({ name, value }) => `    "${name}": "${value}"`).join(',\n');
        updated = updated.slice(0, lastBrace) + `  "vars": {\n${varsObj}\n  },\n` + updated.slice(lastBrace);
      }

      fs.writeFileSync('wrangler.jsonc', updated);
      console.log(`  ✓ ${collectedVars.map(v => v.name).join(', ')} added to wrangler.jsonc`);
    } catch {
      console.error('  ⚠ Could not update wrangler.jsonc — add these vars manually:');
      for (const { name, value } of collectedVars) {
        console.error(`    "${name}": "${value}"`);
      }
    }
  }

  if (collectedSecrets.length === 0 && collectedVars.length === 0 && needsInput.length > 0) {
    console.log('  No keys set. You can add them later with: wrangler secret put <NAME>\n');
  } else if (collectedSecrets.length > 0 || collectedVars.length > 0) {
    console.log();
  }

  return { accountId, bucketName };
}

async function stepCdnDomain({ accountId, bucketName } = {}) {
  console.log('\n  CDN Domain (R2_PUBLIC_URL)');
  console.log('  ─────────────────────────');

  if (!hasWrangler()) {
    console.log('  ⚠ wrangler not found — skipping.\n');
    return;
  }

  // Check if already set
  let existingSecrets = new Set();
  try {
    const secretList = run(`${wranglerCmd()} secret list 2>/dev/null`);
    const parsed = JSON.parse(secretList);
    existingSecrets = new Set(parsed.map(s => s.name));
  } catch { /* ignore */ }

  if (existingSecrets.has('R2_PUBLIC_URL')) {
    console.log('  ✓ R2_PUBLIC_URL already configured\n');
    return;
  }

  const domain = readDomain();
  if (!domain) {
    console.log('  ⚠ Could not read domain from config.yml — skipping CDN setup.\n');
    return;
  }

  if (!accountId || !bucketName) {
    console.log('  ⚠ Could not detect account ID or bucket name — skipping CDN auto-setup.');
    console.log('  Set R2_PUBLIC_URL manually:\n');
    console.log(`    ${wranglerCmd()} secret put R2_PUBLIC_URL\n`);
    console.log('  The value should be https://cdn.yourdomain.com (a Cloudflare-proxied');
    console.log('  subdomain pointing to your R2 bucket).\n');
    return;
  }

  const cdnDomain = `cdn.${domain}`;
  console.log(`  Your blog needs a CDN subdomain for images and media.`);
  console.log(`  I'll create a custom domain on your R2 bucket:\n`);
  console.log(`    ${cdnDomain} → ${bucketName}\n`);
  console.log(`  This requires a DNS record (Cloudflare will add a CNAME automatically).`);
  console.log(`  Your domain "${domain}" must be on Cloudflare DNS.\n`);

  const answer = await ask(`  Set up ${cdnDomain}? [Y/n] `);
  if (answer.toLowerCase() === 'n') {
    console.log('    → skipped. Set R2_PUBLIC_URL manually later.\n');
    return;
  }

  // Get Cloudflare API token: wrangler auth token → env var → ask
  let cfToken;
  try {
    const output = run(`${wranglerCmd()} auth token 2>/dev/null`);
    // wrangler auth token may include a banner line (e.g. "⛅️ wrangler 4.x") — grab the last line
    cfToken = output.split('\n').pop().trim();
  } catch { /* ignore */ }

  if (!cfToken) cfToken = process.env.CLOUDFLARE_API_TOKEN;

  if (!cfToken) {
    console.log('\n  Could not find wrangler credentials automatically.');
    console.log('  Paste a Cloudflare API token to continue, or Enter to skip.');
    console.log('  Create one at: https://dash.cloudflare.com/profile/api-tokens\n');
    const input = await ask('  Cloudflare API token (Enter to skip): ');
    cfToken = input.trim() || null;
  }

  if (!cfToken) {
    console.log('    → skipped. Set up the CDN domain manually:');
    console.log(`    Cloudflare Dashboard → R2 → ${bucketName} → Settings → Custom Domains`);
    console.log(`    Then: ${wranglerCmd()} secret put R2_PUBLIC_URL\n`);
    return;
  }

  // Look up zone ID for the domain
  const cfApi = async (apiPath) => {
    const res = await fetch(`https://api.cloudflare.com/client/v4${apiPath}`, {
      headers: { 'Authorization': `Bearer ${cfToken}` },
    });
    return res.text();
  };

  let zoneId;
  try {
    const zonesResponse = JSON.parse(await cfApi(`/zones?name=${domain}`));
    if (zonesResponse.success && zonesResponse.result?.length > 0) {
      zoneId = zonesResponse.result[0].id;
    } else if (!zonesResponse.success) {
      const errMsg = zonesResponse.errors?.[0]?.message || JSON.stringify(zonesResponse.errors);
      console.log(`\n  ✗ Cloudflare API error: ${errMsg}`);
    }
  } catch (err) {
    console.log(`\n  ✗ API call failed: ${err.message}`);
  }

  if (!zoneId) {
    console.log(`  Could not find zone for "${domain}" on Cloudflare.`);
    console.log('  Make sure your domain is set up on Cloudflare DNS.');
    console.log(`  Then set R2_PUBLIC_URL manually: ${wranglerCmd()} secret put R2_PUBLIC_URL\n`);
    return;
  }

  // Create custom domain on R2 bucket
  try {
    const res = await fetch(`https://api.cloudflare.com/client/v4/accounts/${accountId}/r2/buckets/${bucketName}/domains/custom`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${cfToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ domain: cdnDomain, enabled: true, zoneId }),
    });
    const result = await res.text();
    const parsed = JSON.parse(result);

    if (parsed.success) {
      console.log(`  ✓ Custom domain created: ${cdnDomain}\n`);
    } else {
      const errMsg = parsed.errors?.[0]?.message || 'Unknown error';
      // If domain already exists, that's fine
      if (errMsg.includes('already') || errMsg.includes('exists')) {
        console.log(`  ✓ Custom domain already exists: ${cdnDomain}\n`);
      } else {
        throw new Error(errMsg);
      }
    }
  } catch (err) {
    console.log(`\n  ✗ Failed to create custom domain: ${err.message}`);
    console.log(`  Set it up manually in the Cloudflare dashboard:`);
    console.log(`    R2 → ${bucketName} → Settings → Custom Domains → Connect Domain`);
    console.log(`  Then: ${wranglerCmd()} secret put R2_PUBLIC_URL\n`);
    return;
  }

  // Set R2_PUBLIC_URL secret
  const publicUrl = `https://${cdnDomain}`;
  try {
    execSync(`${wranglerCmd()} secret put R2_PUBLIC_URL`, {
      input: publicUrl,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    console.log(`  ✓ R2_PUBLIC_URL set to ${publicUrl}\n`);
  } catch {
    console.log(`  ✗ Failed to set R2_PUBLIC_URL. Set it manually:`);
    console.log(`    echo "${publicUrl}" | ${wranglerCmd()} secret put R2_PUBLIC_URL\n`);
  }
}

// --- Main ---

async function main() {
  const pkg = JSON.parse(fs.readFileSync('package.json', 'utf-8'));
  const folderName = pkg.name;

  console.log(`\n  Setting up ${folderName} for deployment.`);

  await stepCloudflare(folderName);
  await stepGitHub(folderName);
  const detected = await stepApiKeys();
  await stepCdnDomain(detected);

  // Offer to commit and push
  let remoteUrl;
  try {
    remoteUrl = run('git remote get-url origin');
  } catch { /* no remote */ }

  if (remoteUrl) {
    console.log('  ──────────────────────');
    const deploy = await ask('  Commit and push to trigger first deploy? [Y/n] ');
    if (deploy.toLowerCase() !== 'n') {
      execSync('git add wrangler.jsonc', { stdio: 'pipe' });
      try {
        execSync('git commit -m "setup complete"', { stdio: 'pipe' });
      } catch {
        // nothing to commit — that's fine
      }
      execSync('git push -u origin main', { stdio: 'inherit' });

      const actionsUrl = remoteUrl
        .replace(/\.git$/, '')
        .replace('git@github.com:', 'https://github.com/')
        + '/actions';
      console.log(`\n  ✓ Pushed! Watch your first deploy at:\n\n    ${actionsUrl}\n`);
    } else {
      console.log('\n  When you\'re ready:\n');
      console.log('    git add wrangler.jsonc && git commit -m "setup complete" && git push -u origin main\n');
    }
  } else {
    console.log('  ──────────────────────');
    console.log('  All done! Commit and push to deploy:\n');
    console.log('    git add wrangler.jsonc && git commit -m "setup complete" && git push -u origin main\n');
  }

  rl.close();
}

main().catch((err) => {
  console.error('  Error:', err.message);
  process.exit(1);
});
