// Auto-generated by `npm run sync` — local changes will be overwritten.
// Content collection definitions provided by the whereto-bike package.
export { collections } from 'whereto-bike/content-collections';
