// Auto-generated by `npm run sync` — local changes will be overwritten.
// Content collection definitions provided by the bike-app-astro package.
export { collections } from 'bike-app-astro/content-collections';
