// Auto-generated by `npm run sync` — local changes will be overwritten.
// Delegates auth, CSP, and session handling to the whereto-bike package.
export { onRequest } from 'whereto-bike/middleware';
