// Auto-generated by `npm run sync` — local changes will be overwritten.
// Delegates auth, CSP, and session handling to the bike-app-astro package.
export { onRequest } from 'bike-app-astro/middleware';
