/**
 * Icon Path Generator
 * ===================
 *
 * Scans source files for Phosphor icon names used in Preact components,
 * reads the SVG path data from @phosphor-icons/core, and generates
 * src/components/icon-paths.ts — a browser-safe registry of SVG inner
 * content keyed by "{name}/{weight}".
 *
 * Run: npx tsx scripts/build-icon-paths.ts
 *
 * How it finds icons:
 *   1. Grep .tsx files for <Icon name="..." — direct usage
 *   2. Grep .astro/.tsx files for icon: '...' — props passed to islands
 *   3. Include both regular and fill weights for every icon found
 *      (fill is needed for active/toggle states)
 */
import fs from 'node:fs';
import path from 'node:path';

const PROJECT_ROOT = path.resolve(import.meta.dirname, '..');
const SRC_DIR = path.join(PROJECT_ROOT, 'src');
const OUTPUT_FILE = path.join(SRC_DIR, 'components', 'icon-paths.ts');
const PHOSPHOR_DIR = path.join(PROJECT_ROOT, 'node_modules', '@phosphor-icons', 'core', 'assets');

const WEIGHTS = ['regular', 'fill'] as const;

/** Recursively collect files matching extensions. */
function collectFiles(dir: string, extensions: string[]): string[] {
  const results: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...collectFiles(full, extensions));
    } else if (extensions.some(ext => entry.name.endsWith(ext))) {
      results.push(full);
    }
  }
  return results;
}

/** Extract icon names from source files. */
function findUsedIcons(): Set<string> {
  const icons = new Set<string>();

  const tsxFiles = collectFiles(SRC_DIR, ['.tsx']);
  const astroFiles = collectFiles(SRC_DIR, ['.astro']);

  // Pattern 1: <Icon name="icon-name" — component usage in TSX (must be preceded by <Icon)
  const iconJsxRe = /<Icon\b[^>]*\bname="([a-z][a-z0-9-]*)"/g;

  // Pattern 2: icon: 'icon-name' or icon: "icon-name" — props passed to Preact islands
  const iconPropRe = /\bicon:\s*['"]([a-z][a-z0-9-]*)['"]/g;

  for (const file of tsxFiles) {
    if (file === OUTPUT_FILE) continue;
    const content = fs.readFileSync(file, 'utf-8');
    for (const match of content.matchAll(iconJsxRe)) {
      icons.add(match[1]);
    }
  }

  // Scan both .astro and .tsx for icon prop objects (e.g. labels array with icon: '...')
  for (const file of [...tsxFiles, ...astroFiles]) {
    if (file === OUTPUT_FILE) continue;
    const content = fs.readFileSync(file, 'utf-8');
    for (const match of content.matchAll(iconPropRe)) {
      icons.add(match[1]);
    }
  }

  return icons;
}

/** Read SVG inner content (everything between the outer <svg> tags). */
function extractSvgInner(svgPath: string): string | null {
  if (!fs.existsSync(svgPath)) return null;
  const content = fs.readFileSync(svgPath, 'utf-8');
  // Extract inner content between <svg ...> and </svg>
  const match = content.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  return match ? match[1].trim() : null;
}

/** Resolve SVG file path for a given icon name and weight. */
function svgPath(name: string, weight: string): string {
  const filename = weight === 'regular' ? `${name}.svg` : `${name}-${weight}.svg`;
  return path.join(PHOSPHOR_DIR, weight, filename);
}

// --- Main ---

const usedIcons = findUsedIcons();
if (usedIcons.size === 0) {
  console.log('[icon-paths] No icons found in source files');
  process.exit(0);
}

const sorted = [...usedIcons].sort();
console.log(`[icon-paths] Found ${sorted.length} icons: ${sorted.join(', ')}`);

const entries: string[] = [];
let missing = 0;

for (const name of sorted) {
  for (const weight of WEIGHTS) {
    const filePath = svgPath(name, weight);
    const inner = extractSvgInner(filePath);
    if (inner) {
      const key = `${name}/${weight}`;
      // Escape backticks and ${} in template literal
      const escaped = inner.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
      entries.push(`  '${key}':\n    \`${escaped}\`,`);
    } else {
      // Fill weight may not exist for all icons — that's fine
      if (weight === 'regular') {
        console.warn(`[icon-paths] WARNING: missing regular weight for "${name}"`);
        missing++;
      }
    }
  }
}

if (missing > 0) {
  console.error(`[icon-paths] ${missing} icons missing regular weight — check icon names`);
  process.exit(1);
}

const output = `/**
 * AUTO-GENERATED by scripts/build-icon-paths.ts — do not edit manually.
 *
 * Pre-extracted SVG inner content for Phosphor icons used in Preact components.
 * Browser-safe — no Node.js APIs. Keys follow "{name}/{weight}" format.
 */
export const iconPaths: Record<string, string> = {
${entries.join('\n')}
};
`;

fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
console.log(`[icon-paths] Generated ${OUTPUT_FILE} (${entries.length} entries)`);
