name: CI

on:
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    if: github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/_build-and-deploy.yml
    with:
      deploy: true
      environment: staging
      wrangler-env: staging
      disable-analytics: true
      update-screenshots: true
    secrets:
      DATA_REPO_DEPLOY_KEY: ${{ secrets.DATA_REPO_DEPLOY_KEY }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      GOOGLE_MAPS_STATIC_API_KEY: ${{ secrets.GOOGLE_MAPS_STATIC_API_KEY }}

  test-dependabot:
    if: github.actor == 'dependabot[bot]'
    uses: ./.github/workflows/_build-and-deploy.yml
    with:
      deploy: false
      update-screenshots: false
    secrets:
      DATA_REPO_DEPLOY_KEY: ${{ secrets.DATA_REPO_DEPLOY_KEY }}
      GOOGLE_MAPS_STATIC_API_KEY: ${{ secrets.GOOGLE_MAPS_STATIC_API_KEY }}
