name: Deploy Staging

on:
  workflow_dispatch:
  repository_dispatch:
    types: [staging-data-updated]

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_build-city.yml
    with:
      city: ottawa
      environment: staging
      wrangler-env: staging
      deploy: true
      run-migrations: true
      data-ref: staging
      disable-analytics: true
      app-ref: ${{ github.event.client_payload.app_branch || '' }}
    secrets:
      DATA_REPO_DEPLOY_KEY: ${{ secrets.DATA_REPO_DEPLOY_KEY }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      GOOGLE_MAPS_STATIC_API_KEY: ${{ secrets.GOOGLE_MAPS_STATIC_API_KEY }}
