name: Deploy Staging

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_build-and-deploy.yml
    with:
      environment: staging
      deploy: true
      wrangler-env: staging
      disable-analytics: true
    secrets:
      DATA_REPO_DEPLOY_KEY: ${{ secrets.DATA_REPO_DEPLOY_KEY }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      GOOGLE_MAPS_STATIC_API_KEY: ${{ secrets.GOOGLE_MAPS_STATIC_API_KEY }}
